<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
    <AssemblyTitle>Hytale French Patch Installer</AssemblyTitle>
    <Product>Hytale French Translation Pack</Product>
    <Version>0.6.8.1</Version>
    <Authors>jeremiejt38</Authors>
  </PropertyGroup>
</Project>
